version: '3.7'

services:
  php:
    restart: on-failure
    build:
      context: ./docker/services/php
      args:
        - PHP_VERSION=7.3-fpm
    env_file:
      - .docker.env
    volumes:
      - ./:${DOCKER_VOLUME_CODE_PATH}
      - ./docker/services/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  nginx:
    build: ./docker/services/nginx
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./:${DOCKER_VOLUME_CODE_PATH}
      - ./docker/services/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    ports:
      - 8080:80

  mysql:
    restart: on-failure
    build:
      context: ./docker/services/mysql
      args:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_PORT=${DB_PORT}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/services/mysql/config-overrides.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/volums/database/:/var/lib/mysql

  node:
    image: node:12.14-alpine
    volumes:
      - ./:${DOCKER_VOLUME_CODE_PATH}
    working_dir: ${DOCKER_VOLUME_CODE_PATH}

  redis:
    restart: on-failure
    build: ./docker/services/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-webui:
    image: erikdubbelboer/phpredisadmin
    environment:
      - ADMIN_USER=${DOCKER_REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${DOCKER_REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${DOCKER_REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${DOCKER_REDIS_WEBUI_CONNECT_PORT}
    ports:
      - "${DOCKER_REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
